import Head from "next/head";
import { AiFillLinkedin } from "react-icons/ai";
import { BsFillMoonStarsFill, BsSpotify } from "react-icons/bs";
import { useState } from "react";
import me from "../public/marksamurai.png";
import Image from "next/image";
import Link from "next/link";
import Header from "../../components/Header";
import Card from "../../components/Card";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <Header />

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-slate-200 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <div className="text-center p-10 py-10"></div>

          <Card />
        </section>
      </main>
    </div>
  );
}
